# Schemas module exports
from app.schemas.common import (
    ResponseMessage,
    ErrorResponse,
    PaginationParams,
    PaginatedResponse,
    HealthCheckResponse,
    StoreInfo,
)
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserRegister,
    UserUpdate,
    UserRoleUpdate,
    UserResponse,
    UserPublicResponse,
    LoginRequest,
    LoginResponse,
    TokenPayload,
)
from app.schemas.product import (
    CategoryBase,
    CategoryCreate,
    CategoryUpdate,
    CategoryResponse,
    ProductBase,
    ProductCreate,
    ProductUpdate,
    InventoryUpdate,
    ProductResponse,
    ProductListResponse,
)
from app.schemas.order import (
    OrderItemCreate,
    OrderItemResponse,
    OrderCreate,
    OrderUpdate,
    OrderStatusUpdate,
    OrderResponse,
    OrderListResponse,
    OrderSummary,
)
from app.schemas.prebooking import (
    PreBookingItemCreate,
    PreBookingItemUpdate,
    PreBookingItemResponse,
    PreBookingCreate,
    PreBookingUpdate,
    PreBookingStoreResponse,
    PreBookingResponse,
    PreBookingListResponse,
    PreBookingSummary,
)
from app.schemas.repair import (
    RepairInquiryCreate,
    RepairInquiryUpdate,
    RepairStaffUpdate,
    RepairInquiryResponse,
    RepairInquiryListResponse,
    RepairInquirySummary,
    RepairServiceInfo,
    NotRepairedItemsResponse,
)

__all__ = [
    # Common
    "ResponseMessage",
    "ErrorResponse",
    "PaginationParams",
    "PaginatedResponse",
    "HealthCheckResponse",
    "StoreInfo",
    # User
    "UserBase",
    "UserCreate",
    "UserRegister",
    "UserUpdate",
    "UserRoleUpdate",
    "UserResponse",
    "UserPublicResponse",
    "LoginRequest",
    "LoginResponse",
    "TokenPayload",
    # Product
    "CategoryBase",
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryResponse",
    "ProductBase",
    "ProductCreate",
    "ProductUpdate",
    "InventoryUpdate",
    "ProductResponse",
    "ProductListResponse",
    # Order
    "OrderItemCreate",
    "OrderItemResponse",
    "OrderCreate",
    "OrderUpdate",
    "OrderStatusUpdate",
    "OrderResponse",
    "OrderListResponse",
    "OrderSummary",
    # Pre-booking
    "PreBookingItemCreate",
    "PreBookingItemUpdate",
    "PreBookingItemResponse",
    "PreBookingCreate",
    "PreBookingUpdate",
    "PreBookingStoreResponse",
    "PreBookingResponse",
    "PreBookingListResponse",
    "PreBookingSummary",
    # Repair
    "RepairInquiryCreate",
    "RepairInquiryUpdate",
    "RepairStaffUpdate",
    "RepairInquiryResponse",
    "RepairInquiryListResponse",
    "RepairInquirySummary",
    "RepairServiceInfo",
    "NotRepairedItemsResponse",
]
